# Generated by Django 5.1.7 on 2025-04-22 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
