# Generated by Django 5.1.1 on 2025-04-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_delete_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
