# Generated by Django 5.1.1 on 2025-04-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_chatsession_session_id_chatsession_ended_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('percentage', models.IntegerField(default=0)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
