# Generated by Django 5.1.1 on 2025-04-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastedValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('forecasted_value', models.FloatField()),
            ],
        ),
    ]
