# Generated by Django 5.1.7 on 2025-05-01 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_forecastedvalue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForecastedValue',
        ),
    ]
